services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: decision-dev
    ports:
      - "8001:8000"  # Porta local 8001 redireciona para 8000 no container
    volumes:
      - .:/app  # Sincroniza o diretório atual com o container
      - ./models:/app/models  
    env_file:
      - .env.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus-dev
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
  
  grafana:
      image: grafana/grafana
      container_name: grafana-dev
      ports:
        - "3000:3000"
      volumes:
        - grafana-data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus

volumes:
  grafana-data: