version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: decision-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: always
