
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: decision-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus-dev
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
  
  grafana:
      image: grafana/grafana
      container_name: grafana-dev
      ports:
        - "3000:3000"
      volumes:
        - grafana-data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus

volumes:
  grafana-data: