services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: decision-dev
    ports:
      - "8001:8000"  # Porta local 8001 redireciona para 8000 no container
    volumes:
      - .:/app  # Sincroniza o diretório atual com o container
      - ./models:/app/models  
    env_file:
      - .env.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
