version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decision-prod
    ports:
      - "8001:8000"  
    volumes:
      - .:/app               
      - ./models:/app/models  
    env_file:
      - .env.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
