services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decision-prod
    ports:
      - "8001:8000"  
    volumes:
      - .:/app               
    env_file:
      - .env.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload