{
 "title": "Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status do Serviço",
   "type": "stat",
   "description": "Mostra se o serviço está up ou down.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi-app\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (%)",
   "type": "timeseries",
   "description": "Mostra o uptime para o período analisado.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"fastapi-app\"}[$__interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Requisição HTTP",
   "type": "timeseries",
   "description": "Aqui são mostradas métricas de Total de Requests HTTP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requsições HTTP",
   "type": "timeseries",
   "description": "Aqui são mostrados todos os requests Http da aplicação em quantidade total.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "increase(http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Total de Requisições HTTP por Método",
   "type": "timeseries",
   "description": "Este gráfico mostra o total de acréscimo de requisições HTTP no período.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(method) (increase(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições HTTP por Status Code",
   "type": "timeseries",
   "description": "Este gráfico mostra o total de acréscimo de requisições HTTP no período.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Requisições HTTP por Método",
   "type": "timeseries",
   "description": "Este gráfico mostra o total de acréscimo de requisições HTTP no período.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Requisições HTTP por Status Code",
   "type": "timeseries",
   "description": "Este gráfico mostra o total de acréscimo de requisições HTTP no período.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Requisições HTTP por Rota",
   "type": "timeseries",
   "description": "Este gráfico mostra o total de acréscimo de requisições HTTP no período.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições HTTP por Rota",
   "type": "timeseries",
   "description": "Este gráfico mostra o total de acréscimo de requisições HTTP no período.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(handler) (increase(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média",
   "type": "timeseries",
   "description": "Mostra a latência da requisição para cada endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[$__rate_interval]) / rate(http_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência - Percentil 95% - AJUSTAR",
   "type": "histogram",
   "description": "Este gráfico mostra ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Erros (Status 5XX) ",
   "type": "timeseries",
   "description": "Esse gráfico mostra a taxa de erros, responses com status code 5XX.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}